### ISSUE TITLE
[BACKEND]: Add request body validators

### ISSUE THREAD

**Issue by Timothy-py** [AfriSplash-Remotely/Afrisplash-Backend#135]
### Increasing Access

API

### Feature Request details

Use Joi to validate incoming request body

**Comment by Hrx4** [comment]
can you please tell more about the issue?

**Comment by Timothy-py** [comment]
Most of the API resources(endpoints) do not have request body validators

Use Joi package to implement this - https://joi.dev/api/?v=17.9.1

Resources that needs this include, Auth, Candidate, Recruiter, Company etc.

Take a look at "middleware/validators" directory and see a sample of what i implemented there

**Comment by avinashji1302** [comment]
Please assign me this

**Comment by t-bello7** [comment]
@avinashji1302 Could you check out another issue?

**Comment by avinashji1302** [comment]
> @avinashji1302 Could you check out another issue?

Yes... I will check
