### ISSUE TITLE
[BACKEND] Comment and Reply APIs for Blog Post

### ISSUE THREAD

**Issue by Timothy-py** [AfriSplash-Remotely/Afrisplash-Backend#146]
### Increasing Access

Comment and Reply functionality

### Feature Request details

Comment and Reply functionality

**Comment by Ilesanmi-Erioluwa-Victor** [comment]
@Timothy-py , assign this to me.

**Comment by Timothy-py** [comment]
@Ilesanmi-Erioluwa-Victor Yeah you can proceed to work on it.
