### ISSUE TITLE
[BACKEND] Email Function

### ISSUE THREAD

**Issue by romzy234** [AfriSplash-Remotely/Afrisplash-Backend#17]
## Goal
* Sending Email Through the Server 
* Sending Email Through Multiple Accounts
* Using a Function To Send Email
* The Ability to create Template And Call It in the Function Above

**Note**: Issues would be created to style email So Build with plain HTML for the starter 

## List of Email Templates Needed
*  Welcome
* Forgot Password
* Signup Verification
* New Notification 
* New Job Offer
* Account Verification 

More would be added as the building goes on 

All current email templates are transactional mail
Bulk Email Would be handled using ```MailGun```

## Email Account Needed 
* noreply@afrisplash.com
* admin@afrisplash.com
* notify@afrisplash.com ( low priority )

@adugamayuba @t-bello7 -- Howfar 

@CodigoGod here is the list of email screens required

**Comment by romzy234** [comment]
Functions Have Been Written 
Deployment and a Valid MailGun Account are Required @adugamayuba @CodigoGod

**Comment by adugamayuba** [comment]
Hi @Cyril Ogoh ***@***.***> will Mailjet work?

**Comment by romzy234** [comment]
I haven't worked with mailjet

let me run my research

**Comment by romzy234** [comment]
So I Did my research and I prefer working with mailgun

Mainly cause I didn't understand the flow of mail jet and due to the time of delivery being close

**Comment by romzy234** [comment]
Sending of Email Has Been tested and is ready for implementation
