### ISSUE TITLE
[BACKEND] Admin: API that returns the total number of admins on the platform

### ISSUE THREAD

**Issue by Timothy-py** [AfriSplash-Remotely/Afrisplash-Backend#44]

**Comment by Paras0750** [comment]
I would like to work on this issue, 
by adding admin route and searching in the database

**Comment by Timothy-py** [comment]
> I would like to work on this issue, by adding admin route and searching in the database

Alright, hold on a bit pls. I'm about to finish with the api for inviting admins. When I'm done, I'll inform everyone to pick issues to work on. Thanks.
