### ISSUE TITLE
Fix email templates not loading static files

### ISSUE THREAD

**Issue by Timothy-py** [AfriSplash-Remotely/Afrisplash-Backend#65]

**Comment by Timothy-py** [comment]
![afrisplash](https://github.com/AfriSplash-Remotely/Afrisplash-Backend/assets/49001006/d49839bd-1139-4df5-a575-ff44ac5dd068)

**Comment by Timothy-py** [comment]
@Nancy4321 pls let's fix a time to look into this together, probably after the meeting on Tuesday

**Comment by Nancy4321** [comment]
Ok. Sure
